name: Github Pages

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Setup Node
      uses: actions/setup-node@v1
    - name: Build and deploy to GitHub Pages
      run: |
        git config --global user.email "mike1808@users.noreply.github.com" && \
        git config --global user.name "Mikael Manukyan" && \
        echo "machine github.com login mike1808 password ${{ secrets.ACCESS_TOKEN }}" > ~/.netrc && \
        cd website && yarn install && GIT_USER=mike1808 yarn run publish-gh-pages
